# Generated by Django 2.0.2 on 2018-02-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraftType', models.CharField(max_length=30)),
                ('tailNumber', models.CharField(max_length=30)),
                ('numberOfSeats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('timeZone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingNumber', models.CharField(max_length=6)),
                ('numberOfSeats', models.IntegerField()),
                ('status', models.CharField(max_length=6)),
                ('invalidAtDateTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNumber', models.CharField(max_length=6)),
                ('departureDateTime', models.DateTimeField()),
                ('arrivalDateTime', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('seatPrice', models.IntegerField()),
                ('seatCost', models.IntegerField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.Aircraft')),
                ('departureAirport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='airline.Airport')),
                ('destinationAirport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='airline.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refLocal', models.CharField(max_length=30)),
                ('refExternal', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('wasPaid', models.BooleanField()),
                ('stamp', models.CharField(max_length=30)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('passportNumber', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.URLField()),
                ('accountNumber', models.CharField(max_length=30)),
                ('loginName', models.CharField(max_length=30)),
                ('loginPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.Flight'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(to='airline.Passenger'),
        ),
    ]
