# Generated by Django 2.0.2 on 2018-02-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_auto_20180227_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='seatCost',
        ),
    ]
