# Generated by Django 2.0.2 on 2018-02-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_remove_flight_seatcost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='fullName',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='passenger',
            name='phoneNumber',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='surname',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger',
            name='nationality',
            field=models.CharField(default='Not known', max_length=30),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passportNumber',
            field=models.CharField(default='Not known', max_length=9),
        ),
    ]
