# Generated by Django 2.0.2 on 2018-02-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0005_flight_seatsleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='invalidAtDateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(default='None', to='airline.Passenger'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='ONHOLD', max_length=6),
        ),
    ]
